#!/bin/bash
if [ $EUID != 0 ]; then
    echo 'Você precisa ser root para instalar certificados.'
    exit $?
fi

# Diretório onde os certificados serão instalados
cert_path=`openssl version -d|sed 's/.*\"\(.*\)\"/\1/g'`/certs

# Path para o certificado da Cielo
ecommerce=$cert_path/ecommerce-cielo.crt
# Path para o certificado da intermediária
intermediaria=$cert_path/intermediaria-cielo.crt
# Path para o certificado raiz
raiz=$cert_path/raiz-cielo.crt

# Instalação do certificado raiz
echo "Criando certificado raiz em $raiz"

(cat << 'RAIZ-CIELO'
-----BEGIN CERTIFICATE-----
MIIE0zCCA7ugAwIBAgIQGNrRniZ96LtKIVjNzGs7SjANBgkqhkiG9w0BAQUFADCB
yjELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMR8wHQYDVQQL
ExZWZXJpU2lnbiBUcnVzdCBOZXR3b3JrMTowOAYDVQQLEzEoYykgMjAwNiBWZXJp
U2lnbiwgSW5jLiAtIEZvciBhdXRob3JpemVkIHVzZSBvbmx5MUUwQwYDVQQDEzxW
ZXJpU2lnbiBDbGFzcyAzIFB1YmxpYyBQcmltYXJ5IENlcnRpZmljYXRpb24gQXV0
aG9yaXR5IC0gRzUwHhcNMDYxMTA4MDAwMDAwWhcNMzYwNzE2MjM1OTU5WjCByjEL
MAkGA1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMR8wHQYDVQQLExZW
ZXJpU2lnbiBUcnVzdCBOZXR3b3JrMTowOAYDVQQLEzEoYykgMjAwNiBWZXJpU2ln
biwgSW5jLiAtIEZvciBhdXRob3JpemVkIHVzZSBvbmx5MUUwQwYDVQQDEzxWZXJp
U2lnbiBDbGFzcyAzIFB1YmxpYyBQcmltYXJ5IENlcnRpZmljYXRpb24gQXV0aG9y
aXR5IC0gRzUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCvJAgIKXo1
nmAMqudLO07cfLw8RRy7K+D+KQL5VwijZIUVJ/XxrcgxiV0i6CqqpkKzj/i5Vbex
t0uz/o9+B1fs70PbZmIVYc9gDaTY3vjgw2IIPVQT60nKWVSFJuUrjxuf6/WhkcIz
SdhDY2pSS9KP6HBRTdGJaXvHcPaz3BJ023tdS1bTlr8Vd6Gw9KIl8q8ckmcY5fQG
BO+QueQA5N06tRn/Arr0PO7gi+s3i+z016zy9vA9r911kTMZHRxAy3QkGSGT2RT+
rCpSx4/VBEnkjWNHiDxpg8v+R70rfk/Fla4OndTRQ8Bnc+MUCH7lP59zuDMKz10/
NIeWiu5T6CUVAgMBAAGjgbIwga8wDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8E
BAMCAQYwbQYIKwYBBQUHAQwEYTBfoV2gWzBZMFcwVRYJaW1hZ2UvZ2lmMCEwHzAH
BgUrDgMCGgQUj+XTGoasjY5rw8+AatRIGCx7GS4wJRYjaHR0cDovL2xvZ28udmVy
aXNpZ24uY29tL3ZzbG9nby5naWYwHQYDVR0OBBYEFH/TZafC3ey78DAJ80M5+gKv
MzEzMA0GCSqGSIb3DQEBBQUAA4IBAQCTJEowX2LP2BqYLz3q3JktvXf2pXkiOOzE
p6B4Eq1iDkVwZMXnl2YtmAl+X6/WzChl8gGqCBpH3vn5fJJaCGkgDdk+bW48DW7Y
5gaRQBi5+MHt39tBquCWIMnNZBU4gcmU7qKEKQsTb47bDN0lAtukixlE0kF6BWlK
WE9gyn6CagsCqiUXObXbf+eEZSqVir2G3l6BFoMtEMze/aiCKm0oHw0LxOXnGiYZ
4fQRbxC1lfznQgUy286dUV4otp6F01vvpX1FQHKOtw5rDgb7MzVIcbidJ4vEZV8N
hnacRHr2lVz2XTIIM6RUthg/aFzyQkqFOFSDX9HoLPKsEdao7WNq
-----END CERTIFICATE-----
RAIZ-CIELO
) > $raiz

echo "Instalando o certificado raiz"

# Criando um link simbólico para o certificado utilizando seu hash
ln -s $raiz $cert_path/`openssl x509 -noout -hash -in $raiz`.0 &> /dev/null

# Verificando se o certificado foi instalado corretamente
openssl verify -CApath $cert_path $raiz

# Instalação do certificado da intermediária
echo "Criando certificado da intermediária em $intermediaria"

(cat << 'INTERMEDIARIA-CIELO'
-----BEGIN CERTIFICATE-----
MIIFKzCCBBOgAwIBAgIQfuFKb2/v8tN/P61lTTratDANBgkqhkiG9w0BAQsFADCB
yjELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMR8wHQYDVQQL
ExZWZXJpU2lnbiBUcnVzdCBOZXR3b3JrMTowOAYDVQQLEzEoYykgMjAwNiBWZXJp
U2lnbiwgSW5jLiAtIEZvciBhdXRob3JpemVkIHVzZSBvbmx5MUUwQwYDVQQDEzxW
ZXJpU2lnbiBDbGFzcyAzIFB1YmxpYyBQcmltYXJ5IENlcnRpZmljYXRpb24gQXV0
aG9yaXR5IC0gRzUwHhcNMTMxMDMxMDAwMDAwWhcNMjMxMDMwMjM1OTU5WjB3MQsw
CQYDVQQGEwJVUzEdMBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xHzAdBgNV
BAsTFlN5bWFudGVjIFRydXN0IE5ldHdvcmsxKDAmBgNVBAMTH1N5bWFudGVjIENs
YXNzIDMgRVYgU1NMIENBIC0gRzMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQDYoWV0I+grZOIy1zM3PY71NBZI3U9/hxz4RCMTjvsR2ERaGHGOYBYmkpv9
FwvhcXBC/r/6HMCqo6e1cej/GIP23xAKE2LIPZyn3i4/DNkd5y77Ks7Imn+Hv9hM
BBUyydHMlXGgTihPhNk1++OGb5RT5nKKY2cuvmn2926OnGAE6yn6xEdC0niY4+wL
pZLct5q9gGQrOHw4CVtm9i2VeoayNC6FnpAOX7ddpFFyRnATv2fytqdNFB5suVPu
IxpOjUhVQ0GxiXVqQCjFfd3SbtICGS97JJRL6/EaqZvjI5rq+jOrCiy39GAI3Z8c
zd0tAWaAr7MvKR0juIrhoXAHDDQPAgMBAAGjggFdMIIBWTAvBggrBgEFBQcBAQQj
MCEwHwYIKwYBBQUHMAGGE2h0dHA6Ly9zMi5zeW1jYi5jb20wEgYDVR0TAQH/BAgw
BgEB/wIBADBlBgNVHSAEXjBcMFoGBFUdIAAwUjAmBggrBgEFBQcCARYaaHR0cDov
L3d3dy5zeW1hdXRoLmNvbS9jcHMwKAYIKwYBBQUHAgIwHBoaaHR0cDovL3d3dy5z
eW1hdXRoLmNvbS9ycGEwMAYDVR0fBCkwJzAloCOgIYYfaHR0cDovL3MxLnN5bWNi
LmNvbS9wY2EzLWc1LmNybDAOBgNVHQ8BAf8EBAMCAQYwKQYDVR0RBCIwIKQeMBwx
GjAYBgNVBAMTEVN5bWFudGVjUEtJLTEtNTMzMB0GA1UdDgQWBBQBWavn3ToLWaZk
Y9bPIAdX1ZHnajAfBgNVHSMEGDAWgBR/02Wnwt3su/AwCfNDOfoCrzMxMzANBgkq
hkiG9w0BAQsFAAOCAQEAQgFVe9AWGl1Y6LubqE3X89frE5SG1n8hC0e8V5uSXU8F
nzikEHzPg74GQ0aNCLxq1xCm+quvL2GoY/Jl339MiBKIT7Np2f8nwAqXkY9W+4nE
qLuSLRtzsMarNvSWbCAI7woeZiRFT2cAQMgHVHQzO6atuyOfZu2iRHA0+w7qAf3P
eHTfp61Vt19N9tY/4IbOJMdCqRMURDVLtt/JYKwMf9mTIUvunORJApjTYHtcvNUw
LwfORELEC5n+5p/8sHiGUW3RLJ3GlvuFgrsEL/digO9i2n/2DqyQuFa9eT/ygG6j
2bkPXToHHZGThkspTOHcteHgM52zyzaRS/6htO7w+Q==
-----END CERTIFICATE-----
INTERMEDIARIA-CIELO
) > $intermediaria

echo "Instalando certificado da intermediária"

# Criando um link simbólico para o certificado utilizando seu hash
ln -s $intermediaria $cert_path/`openssl x509 -noout -hash -in $intermediaria`.0 &> /dev/null

# Verificando se o certificado foi instalado corretamente
openssl verify -CApath $cert_path $intermediaria

# Instalação do certificado Cielo
echo "Criando certificado ecommerce da Cielo em $ecommerce"

(cat << 'ECOMMERCE-CIELO'
-----BEGIN CERTIFICATE-----
MIIGeTCCBWGgAwIBAgIQPu+zheuMvnt1uR3mtf6utjANBgkqhkiG9w0BAQsFADB3
MQswCQYDVQQGEwJVUzEdMBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xHzAd
BgNVBAsTFlN5bWFudGVjIFRydXN0IE5ldHdvcmsxKDAmBgNVBAMTH1N5bWFudGVj
IENsYXNzIDMgRVYgU1NMIENBIC0gRzMwHhcNMTYwOTE1MDAwMDAwWhcNMTcwOTE1
MjM1OTU5WjCB8zETMBEGCysGAQQBgjc8AgEDEwJCUjEdMBsGA1UEDxMUUHJpdmF0
ZSBPcmdhbml6YXRpb24xGzAZBgNVBAUTEjAxLjAyNy4wNTgvMDAwMS05MTELMAkG
A1UEBhMCQlIxETAPBgNVBBEMCDA2NDU0MDUwMQswCQYDVQQIDAJTUDEQMA4GA1UE
BwwHQmFydWVyaTEXMBUGA1UECQwOQWxhbWVkYSBHcmFqYXUxEzARBgNVBAoMCkNJ
RUxPIFMuQS4xEjAQBgNVBAsMCUVDT01NRVJDRTEfMB0GA1UEAwwWZWNvbW1lcmNl
LmNpZWxvLmNvbS5icjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL73
eWMjR5erXtpnMaFvvPX1HrPTiNsXpRMXLekRq7BbYdhEyXn0CAhr+q3+DiPzgEHk
QTmYSftc/ZBZO0hYUPzU7qkQH3Pt6nTrMfhBtE4DfJUi1i3o/44Tt7v936M5RKYJ
/uEuzsnV8ZowKIzjnfdM+4nNYQ1LhsjltrDw6OQ5Jd9LJPfWWPxRba401XFHVlda
OqukBXca2qS+jm4WH4vCNIltgAZSQ1/qfd0HYn679e7/TkkGGhYhBVsT3frHRdNF
3+n+B5nYWsgGIwRLMnzILJ6PIjvx2vKE9KyklFWYOshW4MhQEpdsAOmPA3f8TKU4
tAGSn+yu8YaAMXlgxtsCAwEAAaOCAoIwggJ+MCEGA1UdEQQaMBiCFmVjb21tZXJj
ZS5jaWVsby5jb20uYnIwCQYDVR0TBAIwADAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0l
BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMG8GA1UdIARoMGYwBwYFZ4EMAQEwWwYL
YIZIAYb4RQEHFwYwTDAjBggrBgEFBQcCARYXaHR0cHM6Ly9kLnN5bWNiLmNvbS9j
cHMwJQYIKwYBBQUHAgIwGQwXaHR0cHM6Ly9kLnN5bWNiLmNvbS9ycGEwHwYDVR0j
BBgwFoAUAVmr5906C1mmZGPWzyAHV9WR52owKwYDVR0fBCQwIjAgoB6gHIYaaHR0
cDovL3NyLnN5bWNiLmNvbS9zci5jcmwwVwYIKwYBBQUHAQEESzBJMB8GCCsGAQUF
BzABhhNodHRwOi8vc3Iuc3ltY2QuY29tMCYGCCsGAQUFBzAChhpodHRwOi8vc3Iu
c3ltY2IuY29tL3NyLmNydDCCAQUGCisGAQQB1nkCBAIEgfYEgfMA8QB3AN3rHSt6
DU+mIIuBrYFocH4ujp0B1VyIjT0RxM227L7MAAABVy94LRQAAAQDAEgwRgIhAJRA
HBxECQFY4lUP7GvKIZnMZlP/3qiOR8Z9sPuSNXAOAiEA+KwWjbCp5wtViJHZO1yn
ih7osGEdV0sppZsgS79Km/cAdgCkuQmQtBhYFIe7E6LMZ3AKPDWYBPkb37jjd80O
yA3cEAAAAVcveC6UAAAEAwBHMEUCIQC5npEo8ljSfgMGVSj9EIwWFL9cHNyIyF1Z
M+4VbG4N/wIgZ5qmm6so/rclrOoUwjEzGzlahm3LL4vw6HSJvOUsjLgwDQYJKoZI
hvcNAQELBQADggEBAEcCvzP3N5P/hgX2ohUvaQ51CC7pbbbHY+KGJKFNspdK+0gR
w2wRIHGXQVQEXQA+Youj0su8nyhTMsYhlx4IjiZX6R4UPQMDyY7FUmGTyCkHuQH4
znFCfPz0OSh1D5vJ/lEZt9I4OJwFT7uvT2A/TC4TKE5+dXk7c/y086d862EUGZBc
4fmPthmRCbuoqwPq1jPJpl06rKb1zy66Im64ED2FN1/Q9oCbFfCc1vWYGHj9PE2b
e8zMDjS96bmupMGOiVBxTho+BCASo7L023LIoPs+E4EBl4KJIbFNBLi7XRLGhQQE
qn0tJX81DnT8kDehPruZtmog0mwqzYyx3U6UdfE=
-----END CERTIFICATE-----
ECOMMERCE-CIELO
) > $ecommerce

echo "Instalando certificado ecommerce da Cielo"

# Criando um link simbólico para o certificado utilizando seu hash
ln -s $ecommerce $cert_path/`openssl x509 -noout -hash -in $ecommerce`.0 &> /dev/null

# Verificando se o certificado foi instalado corretamente
openssl verify -CApath $cert_path $ecommerce

# Exibindo informações do certificado instalado
openssl x509 -in $ecommerce -text -noout
